server:
    port: 80
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true
mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: lishuo521
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/db_exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
logging:
    level:
        com:
            rabbiter:
                oes:
                    mapper: 'info '